GET http://localhost:3000/all-movies

###
POST http://localhost:3000/create-movie
Content-Type: application/json

{
    "title": "Homem-Aranha: Um Novo Dia",
    "gender": "Ação",
    "ageLimit": 12,
    "duration": 145
}

###
DELETE http://localhost:3000/delete-movie/6

###
PUT http://localhost:3000/edit-movie/1
Content-Type: application/json

{
    "title": "Homem-Aranha: Um Novo Dia",
    "gender": "Ação",
    "ageLimit": 12,
    "duration": 145
}